src/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url, include
from django.contrib import admin

from .views import home, contact, signin, register, signout

urlpatterns = [
    url(r'^$', home, name="home"),
    url(r'^contact/$', contact, name="contact"),
    url(r'^login/$', signin, name="signin"),
    url(r'^logout/$', signout, name="signout"),
    url(r'^register/$', register, name="register"),
    url(r'^admin/', admin.site.urls),
    url(r'^products/', include("products.urls", namespace="products")),
    url(r'^search/', include("search.urls", namespace="search")),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/products/urls.py
from django.conf.urls import url

from .views import ProductListView, ProductDetailView, ProductFeaturedListView, ProductFeaturedDetailView


urlpatterns = [
    url(r'^$', ProductListView.as_view(), name="list"),
    # url(r'^featured/$', ProductFeaturedListView.as_view(), name="products-featured-list"),
    url(r'^(?P<slug>[\w-]+)/$', ProductDetailView.as_view(), name="detail"),
    # url(r'^featured/(?P<slug>[\w-]+)/$', ProductFeaturedDetailView.as_view(), name="product-featured-detail"),
]

src/search/urls.py
from django.conf.urls import url

from .views import SearchProductView


urlpatterns = [
    url(r'^$', SearchProductView.as_view(), name="query"),
]

src/templates/base/css.html
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

src/templates/base/js.html
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

src/templates/base/navbar.html
{% url 'home' as home_url %}
{% url 'products:list' as products_url %}
{% url 'contact' as contact_url %}
{% url 'signin' as signin_url %}
{% url 'signout' as signut_url %}
{% url 'register' as register_url %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
    <a class="navbar-brand" href="{{ home_url }}">eCommerce</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item {% if request.path == home_url %} active {% endif %}">
                <a class="nav-link" href="{{ home_url }}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item {% if request.path == products_url %} active {% endif %}">
                <a class="nav-link" href="{{ products_url }}">Products</a>
            </li>
            <li class="nav-item {% if request.path == contact_url %} active {% endif %}">
                <a class="nav-link" href="{{ contact_url }}">Contact</a>
            </li>
            
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'signout' %}">Logout</a>
                </li>
            {% else %}
                <li class="nav-item {% if request.path == signin_url %} active {% endif %}">
                    <a class="nav-link" href="{{ signin_url }}">Login</a>
                </li>
                <li class="nav-item {% if request.path == register_url %} active {% endif %}">
                    <a class="nav-link" href="{{ register_url }}">Register</a>
                </li>
            {% endif %}
                
        </ul>
        {% include 'search/snippets/search-form.html' %}
    </div>
</nav>