src/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url, include
from django.contrib import admin

from .views import home, contact, signin, register, signout

urlpatterns = [
    url(r'^$', home, name="home"),
    url(r'^contact/$', contact, name="contact"),
    url(r'^login/$', signin, name="signin"),
    url(r'^logout/$', signout, name="signout"),
    url(r'^register/$', register, name="register"),
    url(r'^admin/', admin.site.urls),
    url(r'^products/', include("products.urls", namespace="products")),
    url(r'^search/', include("search.urls", namespace="search")),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/search/urls.py
from django.conf.urls import url

from .views import SearchProductView


urlpatterns = [
    url(r'^$', SearchProductView.as_view(), name="query"),
]

src/search/models.py
from django.db import models

# Create your models here.

src/search/views.py
from django.shortcuts import render
from django.views.generic import ListView

from products.models import Product


class SearchProductView(ListView):
    template_name = "search/view.html"

    def get_queryset(self, *args, **kwargs):
        query = self.request.GET.get('q', None)
        if query is not None:
            return Product.objects.search(query)
        return Product.objects.none()

src/templates/search/snippets/search-form.html
<form method="GET" action="{% url 'search:query' %}" class="form my-2 my-lg-0">
    <div class="input-group">
        <input class="form-control" type="search" placeholder="Search" name="q" aria-label="Search" value="{{ request.GET.q }}">
        <span class="input-group-btn">
            <button class="btn btn-outline-success" type="submit">Search</button>
        </span>
    </div>
</form>